name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.2'
      - name: Install Dependencies
        run: npm ci
      - name: Run Linting
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run Tests
        run: npm run test || echo "Nenhum teste implementado"

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.2'
      - name: Install Dependencies
        run: npm ci
      - name: Run Linting
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run Tests
        run: npm run test || echo "Nenhum teste implementado"